---
title: "Report on Lake Ontario Microbes"
author: "Karina Zhang"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r load packages}
library(tidyverse)
```

# Goal of the report
Here, I create an analysis of environmental and microbial data from Lake Ontario. The goals is to determine how environmental variables like temperature affect the abundance of different Phyla of bacteria. 

# Load the data
# 1) Taxonomy data
```{r load taxon data}
# Load the taxon abundance data
taxon_dirty_df <- 
  read_csv("data/taxon_abundance.csv", skip = 2) %>%
  select(-...10) %>%
  rename(sequence = ...9)

# Load the top of the dataframe
head(taxon_dirty_df, 6)

# Clean the df to cyanobacteria
taxon_clean_df <- 
  taxon_dirty_df %>%
  select(sample_id:Cyanobacteria)

#How many columns? Intuition check!
ncol(taxon_clean_df)
ncol(taxon_dirty_df)
```

# 2) Environmental data
```{r Load data samples}
sample_data_df <- 
  read_csv("data/sample_data.csv")
head(sample_data_df)
```

# Reshaping the data
```{r Reshape data}
taxon_long_df <-
  taxon_clean_df %>%
  pivot_longer(cols = Proteobacteria:Cyanobacteria,
               names_to = "Phylum", values_to = "Abundance")

#Intuition check
nrow(taxon_long_df)
nrow(taxon_clean_df)
```

# Plot taxon data
```{r Plot taxa}
taxon_long_df %>%
  ggplot( aes(x=sample_id, y=Abundance, fill=Phylum)) + 
  geom_col() +
  theme(axis.text.x = element_text(angle = 90))
```







